# ===========================
# PostgreSQL
# ===========================
db.user=motordesk
db.password=motordesk_pass
db.url=jdbc:postgresql://localhost:5432/motordesk
db.driver=org.postgresql.Driver
# ===========================
# JWT
# ===========================
jwt.issuer=ktor-api
jwt.audience=ktor-users
jwt.realm=ktor-app
jwt.secret=super-secret-key
# ===========================
# MongoDB
# ===========================
mongo.user=motordesk
mongo.password=motordesk_pass
mongo.database=motordesk
mongo.url=mongodb://mongodb:27017
# ===========================
# Redis
# ===========================
redis.host=localhost
redis.port=6379
redis.user=motordesk
redis.password=motordesk_pass
