# Database Connection Credentials
db.user=motordesk
db.password=motordesk_pass
db.url=jdbc:postgresql://localhost:5432/motordesk
db.driver=org.postgresql.Driver
jwt.issuer="ktor-api"
jwt.audience="ktor-users"
jwt.realm="ktor-app"
jwt.secret="super-secret-key"