# Database Connection Credentials
db.user=motordesk
db.password=motordesk_pass
db.url=r2dbc:postgresql://localhost:5432/motordesk
db.driver=postgresql
jwt.issuer="ktor-api"
jwt.audience="ktor-users"
jwt.realm="ktor-app"
jwt.secret="super-secret-key"