name: Terraform Azure

on:
  workflow_call:
    inputs:
      new-backend:
        required: false
        type: boolean
        default: false

      environment:
        required: true
        type: string

      image_tag:
        required: true
        type: string

    secrets:
      AZURE_CREDENTIALS:
        required: true

  workflow_dispatch:
    inputs:
      new-backend:
        required: false
        type: boolean
        default: false
      environment:
        description: Azure environment
        required: true
        type: choice
        options:
          - dev
          - qa

      image_tag:
        description: Docker image tag
        required: false
        default: ""
        type: string

jobs:
  terraform-state:
    runs-on: ubuntu-latest
    if: inputs.new-backend == true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Init Backend
        working-directory: infra/terraform/backend
        run: terraform init -input=false

      - name: Terraform Apply Backend
        working-directory: infra/terraform/backend
        run: terraform apply -input=false -auto-approve -var="environment=${{ inputs.environment }}"

  terraform:
    needs: terraform-state
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Get existing backend
        id: local_tfstate
        run: |
          RESOURCE_GROUP_NAME="rg-persistent-motordesk-${{ inputs.environment }}"
          
          STORAGE_ACCOUNT_NAME=$(az storage account list \
            --resource-group "$RESOURCE_GROUP_NAME" \
            --query "[0].name" \
            --output tsv)
          
          CONTAINER_NAME=$(az storage container list \
            --account-name "$STORAGE_ACCOUNT_NAME" \
            --auth-mode login \
            --query "[?name=='tfstate'].name | [0]" \
            --output tsv)
          
          echo "resource_group_name=$RESOURCE_GROUP_NAME" >> "$GITHUB_OUTPUT"
          echo "storage_account_name=$STORAGE_ACCOUNT_NAME" >> "$GITHUB_OUTPUT"
          echo "container_name=$CONTAINER_NAME" >> "$GITHUB_OUTPUT"
          echo "key=motordesk-${{ inputs.environment }}.tfstate" >> "$GITHUB_OUTPUT"

      - name: Terraform Init
        working-directory: infra/terraform/azure
        run: |
          terraform init -input=false -reconfigure \
            -backend-config="resource_group_name=${{ steps.local_tfstate.outputs.resource_group_name }}" \
            -backend-config="storage_account_name=${{ steps.local_tfstate.outputs.storage_account_name }}" \
            -backend-config="container_name=${{ steps.local_tfstate.outputs.container_name }}" \
            -backend-config="key=${{ steps.local_tfstate.outputs.key }}"

      - name: Terraform Fmt
        working-directory: infra/terraform/azure
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        working-directory: infra/terraform/azure
        run: terraform validate

      - name: Terraform Apply
        working-directory: infra/terraform/azure
        run: terraform apply -input=false -auto-approve -var="environment=${{ inputs.environment }}" -var="image_tag=${{ inputs.image_tag }}"
