name: terraform-azure

on:
  workflow_call:
    inputs:
      environment:
        description: "Terraform environment to run"
        required: true
        type: string
      docker-image-tag:
        description: "Docker image tag"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        description: "Terraform environment to run"
        required: false
        default: dev
        type: string
        options:
          - dev
          - qa

      docker-image-tag:
        description: "Docker image tag"
        required: false
        default: ""
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/terraform/azure

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Fmt
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve -var="environment=${{ inputs.environment }}" -var="image_tag=${{ inputs.docker-image-tag }}"
